### ISSUE TITLE
Troxel doesn't load on Linux

### ISSUE THREAD

**Issue by jokerr77** [chrmoritz/Troxel#30]
I'm currently running the Lubuntu 15.04 distro after switching from Windows XP, and everytime I open Troxel, it just shows the gray editor with buttons, but I can't click Edit or see what people have made. When trying to open other menus, they just open then close automatically. Troxel used to work on XP, so i assume it has to do with Linux. I'm currently using Google Chrome Version 44.0.2403.107, but it doesn't load on Firefox either. 

Here's my OS info.
-Version-
Kernel		: Linux 3.19.0-23-generic (i686)
Compiled		: #24-Ubuntu SMP Tue Jul 7 18:52:29 UTC 2015
C Library		: Unknown
Default C Compiler		: Unknown
Distribution		: Ubuntu 15.04
-Current Session-
Computer Name		: NAME-MM061
User Name		: NAME (FULL NAME)
Home Directory		: /home/NAME
Desktop Environment		: LXDE (Lubuntu)
-Misc-
Uptime		: 2 hours, 25 minutes
Load Average		: 0.74, 0.81, 0.77

I hope to see linux support soon, thanks :D

**Comment by chrmoritz** [comment]
Does you current setup [support WebGL](http://webglreport.com/) and if so are other [WebGL examples](http://threejs.org/examples/) working for you? Could you please post the error message from the JavaScript console when opening Troxel.

I guess that you current setup doesn't support WebGL. You can check it out in Google Chrome by going to [chrome://gpu/](chrome://gpu/). If WebGL is marked as unavailable try to update you graphic drivers. If it's still unavailable after that, try to activate the hardware acceleration on unsupported system in Chrome [following this guide](chrome://flags/) and hope you don't run into issues with it.

**Comment by jokerr77** [comment]
Hey it worked! I hardware accelerated and WebGL is supported and Troxel works :) Sorry for the issue, still new to Linux so I wasn't sure if I updated/set things properly.

**Comment by chrmoritz** [comment]
no problem, glad to hear it is working for you now
