### ISSUE TITLE
Unable to import Trove blueprints

### ISSUE THREAD

**Issue by moo3oo3oo3** [chrmoritz/Troxel#34]
I attempted to run `npm run import` but got `npm ERR! missing script: import`. I'm using node v8.11.1 and npm v5.6.0.

**Comment by chrmoritz** [comment]
The Readme was a little outdated and refered to [the old importer](https://github.com/chrmoritz/Troxel/blob/e6747c588d38a63941167d8842c391eb7af8b9da/Gruntfile.coffee#L161) when everything was still in one monorepo. The current improved version of the importer is the one you've already found in [troxeljs/trove-blueprints](https://github.com/troxeljs/trove-blueprints).
